create table game (game_id bigint generated by default as identity, game_type varchar(255), name varchar(255) not null, primary key (game_id))
create table match (match_id bigint generated by default as identity, date_time timestamp, game_game_id bigint, primary key (match_id))
create table player (player_id bigint generated by default as identity, score decimal(19,2), match_match_id bigint, user_user_id bigint, primary key (player_id))
create table ranking (ranking_id bigint generated by default as identity, value decimal(19,2) not null, game_game_id bigint not null, user_user_id bigint not null, primary key (ranking_id))
create table user (user_id bigint generated by default as identity, name varchar(255) not null, primary key (user_id))
alter table game add constraint UK_jare70vqqti665ds3b2eh7rk8 unique (name)
alter table user add constraint UK_gj2fy3dcix7ph7k8684gka40c unique (name)
alter table match add constraint FK1gf3fp6fh6km1227w3n1aout1 foreign key (game_game_id) references game
alter table player add constraint FKs3rkknyit69f3vi96p55eh8i0 foreign key (match_match_id) references match
alter table player add constraint FKi08poxythxcnmt9x8ui8kii8i foreign key (user_user_id) references user
alter table ranking add constraint FKnng63ladcr7k3ms4d5orua74l foreign key (game_game_id) references game
alter table ranking add constraint FKnr0hb49qe8rndwr0e0fgb3bg7 foreign key (user_user_id) references user
